### ISSUE TITLE
repository 'https://github.com/leftthomas/CapsuleLayer.git/' not found

### ISSUE THREAD

**Issue by lefromage** [leftthomas/CCCapsNet#2]
when trying to install

pip install git+https://github.com/leftthomas/CapsuleLayer.git@master

remote: Repository not found.
fatal: repository 'https://github.com/leftthomas/CapsuleLayer.git/' not found
Command "git clone -q https://github.com/leftthomas/CapsuleLayer.git /tmp/pip-req-build-bfyzbtb_" failed with error code 128 in None

looking forward to test
Thanks

**Comment by leftthomas** [comment]
because the paper is under review, so the repository now is private, after the paper is published, the repo will be public.
