### ISSUE TITLE
ImportError: cannot import name 'datasets_iterator' from 'torchnlp.utils'

### ISSUE THREAD

**Issue by anirudhprabhu** [leftthomas/CCCapsNet#3]
Hello , 
I am new to Pytorch and capsule networks. 
I have been trying to run the code you provided and came across the following error while preprocessing the imdb dataset. 
`ImportError: cannot import name 'datasets_iterator' from 'torchnlp.utils'`

I tried to look around for a solution, but failed. I cannot find what version of `torchnlp` has the `datasets_iterator` function, or what the latest version's equivalent is for the same. 

Any help you can provide would help me a lot. 
Thank you!

**Comment by leftthomas** [comment]
@anirudhprabhu，look readme Requirements section first

**Comment by anirudhprabhu** [comment]
Hello @leftthomas 

I have installed everything as shown in the requirements section. There isnt a `datasets_iterator` anymore in `torchnlp.utils`. Which is why I asked the question. Can you at least tell me what version of torchnlp your code uses?
